### ISSUE TITLE
this nginx cp very easy to install

### ISSUE THREAD

**Issue by dynaz** [ozgrozer/jaydon#6]
hi i see this nginx cp very lightweight but what is for user and default password after install to login

**Comment by ozgrozer** [comment]
Thanks for the thoughts but keep in mind that this is not a production-ready control panel so use at your own risk. You can find the login informations in [this](https://github.com/ozgrozer/jaydon/blob/master/src/backend/firstRun.js#L14:L16) file. Username and password is `root` but what have to be done is they have to be auto-generated on install process. If I find some time I'll update the code. Also you can't change the password in panel so you have to change it in MongoDB manually.

**Comment by dynaz** [comment]
thank you do u have time , i want to talk about project
